const bcrypt = require("bcryptjs");
const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      passwordHash: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Michael",
      email: "michael@example.com",
      passwordHash: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Nike Sneakers1",
      slug: "nike-slug",
      category: "sneakers",
      image: "/images/nike.jpeg",
      price: 123,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "1",
      name: "Nike Sneakers12",
      slug: "nike-slug223",
      category: "sneakers",
      image: "/images/nike.jpeg",
      price: 123,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "2",
      name: "Nike Sneakers2",
      slug: "nike-slug1",
      category: "sneakers",
      image: "/images/nike.jpeg",
      price: 345,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "3",
      name: "Nike Sneakers3",
      slug: "nike-slug2",
      category: "sneakers",
      image: "/images/nike.jpeg",
      price: 453,
      countInStock: 0,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "4",
      name: "Nike Sneakers4",
      slug: "nike-slug3",
      category: "sneakers",
      image: "/images/nike3.png",
      price: 234,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "5",
      name: "Nike Sneakers5",
      slug: "nike-slug4",
      category: "sneakers",
      image: "/images/nike4.webp",
      price: 50,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      reviews: 10,
      description: "high quality nikes",
    },
    {
      // _id: "6",
      name: "Nike Sneakers6",
      slug: "nike-slug5",
      category: "sneakers",
      image: "/images/nike.jpeg",
      price: 101,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      reviews: 10,
      description: "high quality nikes",
    },
  ],
};

module.exports = { data };
