export const data = {
  products: [
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
    {
      name: 'Nike Sneakers',
      slug: 'nike-slug',
      category: 'sneakers',
      image: '/images/nike.jpeg',
      price: '100',
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      reviews: 10,
      description: 'high quality nikes',
    },
  ],
};
